import Head from "next/head";
import dynamic from "next/dynamic";
import styled from "styled-components";
import BurgerMenu from "../components/BurgerMenu";

const Map = dynamic(() => import("../components/Map"), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>LOSINGiT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <BurgerMenu />
      </nav>
      <Main>
        <h1>Welcome to LOSINGiT!</h1>
        <h2>
          Have you lost or found something? <br /> Check our map!
        </h2>

        <Map />
      </Main>
    </>
  );
}

const Main = styled.main`
  text-align: center;
`;

const StyledHeadline = styled.h1`
  all: unset;
  font-size: 14rem;
  margin: 3em;
  width: 7em;
  height: 2em;
  position: relative;
  color: white;
  border-radius: 0.5em;
  transition: ease-out 0.9s;
  outline: none;
  background-image: linear-gradient(
    90deg,
    #0065ff,
    #6942ef,
    #6554c0,
    #008cff,
    #0065ff,
    #6942ef
  );
  background-size: 400%;
  background-position: 0% 0%;
  font-size: 2em;
  padding: 0.5em;
`;
